// Code generated by Slice Machine. DO NOT EDIT.

import GithubLink from './GithubLink/index.svelte';
import HeadingOne from './HeadingOne/index.svelte';
import MainImage from './MainImage/index.svelte';
import Paragraph from './Paragraph/index.svelte';

export const components = {
	github_link: GithubLink,
	heading_one: HeadingOne,
	main_image: MainImage,
	paragraph: Paragraph
};
