// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type VisitekaartDocumentDataSlicesSlice =
	| HeadingOneSlice
	| MainImageSlice
	| GithubLinkSlice
	| ParagraphSlice;

/**
 * Content for visitekaart documents
 */
interface VisitekaartDocumentData {
	/**
	 * HeadingOne field in *visitekaart*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: visitekaart.headingone
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	headingone: prismic.RichTextField;

	/**
	 * MainImage field in *visitekaart*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: visitekaart.mainimage
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	mainimage: prismic.ImageField<never>;

	/**
	 * Paragraph field in *visitekaart*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: visitekaart.paragraph
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;

	/**
	 * GithubLink field in *visitekaart*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: visitekaart.githublink
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	githublink: prismic.LinkField;

	/**
	 * Slice Zone field in *visitekaart*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: visitekaart.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<VisitekaartDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *visitekaart*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: visitekaart.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *visitekaart*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: visitekaart.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *visitekaart*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: visitekaart.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * visitekaart document from Prismic
 *
 * - **API ID**: `visitekaart`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VisitekaartDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<VisitekaartDocumentData>,
	'visitekaart',
	Lang
>;

export type AllDocumentTypes = VisitekaartDocument;

/**
 * Primary content in *GithubLink → Primary*
 */
export interface GithubLinkSliceDefaultPrimary {
	/**
	 * GithubLink field in *GithubLink → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: github_link.primary.githublink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	githublink: prismic.LinkField;
}

/**
 * Default variation for GithubLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GithubLinkSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<GithubLinkSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *GithubLink*
 */
type GithubLinkSliceVariation = GithubLinkSliceDefault;

/**
 * GithubLink Shared Slice
 *
 * - **API ID**: `github_link`
 * - **Description**: GithubLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GithubLinkSlice = prismic.SharedSlice<'github_link', GithubLinkSliceVariation>;

/**
 * Primary content in *HeadingOne → Primary*
 */
export interface HeadingOneSliceDefaultPrimary {
	/**
	 * HeadingOne field in *HeadingOne → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: heading_one.primary.headingone
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	headingone: prismic.RichTextField;
}

/**
 * Default variation for HeadingOne Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingOneSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeadingOneSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *HeadingOne*
 */
type HeadingOneSliceVariation = HeadingOneSliceDefault;

/**
 * HeadingOne Shared Slice
 *
 * - **API ID**: `heading_one`
 * - **Description**: HeadingOne
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingOneSlice = prismic.SharedSlice<'heading_one', HeadingOneSliceVariation>;

/**
 * Primary content in *MainImage → Primary*
 */
export interface MainImageSliceDefaultPrimary {
	/**
	 * MainImage field in *MainImage → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_image.primary.mainimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	mainimage: prismic.ImageField<'mainsmall' | 'mainmedium' | 'mainlarge'>;
}

/**
 * Default variation for MainImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainImageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<MainImageSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *MainImage*
 */
type MainImageSliceVariation = MainImageSliceDefault;

/**
 * MainImage Shared Slice
 *
 * - **API ID**: `main_image`
 * - **Description**: MainImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainImageSlice = prismic.SharedSlice<'main_image', MainImageSliceVariation>;

/**
 * Primary content in *Paragraph → Primary*
 */
export interface ParagraphSliceDefaultPrimary {
	/**
	 * paragraph field in *Paragraph → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: paragraph.primary.paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
}

/**
 * Default variation for Paragraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagraphSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ParagraphSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Paragraph*
 */
type ParagraphSliceVariation = ParagraphSliceDefault;

/**
 * Paragraph Shared Slice
 *
 * - **API ID**: `paragraph`
 * - **Description**: Paragraph
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagraphSlice = prismic.SharedSlice<'paragraph', ParagraphSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			VisitekaartDocument,
			VisitekaartDocumentData,
			VisitekaartDocumentDataSlicesSlice,
			AllDocumentTypes,
			GithubLinkSlice,
			GithubLinkSliceDefaultPrimary,
			GithubLinkSliceVariation,
			GithubLinkSliceDefault,
			HeadingOneSlice,
			HeadingOneSliceDefaultPrimary,
			HeadingOneSliceVariation,
			HeadingOneSliceDefault,
			MainImageSlice,
			MainImageSliceDefaultPrimary,
			MainImageSliceVariation,
			MainImageSliceDefault,
			ParagraphSlice,
			ParagraphSliceDefaultPrimary,
			ParagraphSliceVariation,
			ParagraphSliceDefault
		};
	}
}
